name: Build, lint, test

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: scripts/ci/build-and-test.sh
        env:
          NODE_VERSION: ${{ matrix.node-version }}

  build-and-test-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ..\..\gh
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ..\..\gh
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: bash scripts/ci/build-and-test.sh
        shell: bash
        env:
          NODE_VERSION: ${{ matrix.node-version }}