name: Monorepo pipeline

on:
  push:
    branches:
      - "main"
      - "release/**"
      - "hotfix/**"
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

env:
  DOCKER_REGISTRY: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    outputs:
      PUBLISH: ${{ steps.publish_flag.outputs.PUBLISH }}

    steps:
      - uses: actions/checkout@v2

      - name: Generate docker image tag
        id: docker_tags
        run: |
          export GIT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF/refs\/heads\//}}"
          export DOCKER_BRANCH_TAG=$(echo ${GIT_BRANCH} | tr "/." "-" )
          export DOCKER_TAG=${GITHUB_RUN_NUMBER}_${DOCKER_BRANCH_TAG}_${GITHUB_SHA:0:7}
          echo "Docker tag will be ${DOCKER_TAG}"
          echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

      - name: Set publish flag
        id: publish_flag
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            export PUBLISH=false
          else
            export PUBLISH=true
          fi
          echo "PUBLISH=${PUBLISH}" >> $GITHUB_ENV
          echo "::set-output name=PUBLISH::${PUBLISH}"

      - name: Docker login to ECR repo
        if: ${{ env.PUBLISH == 'true'}}
        run: ./ci/docker-login-ecr.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker image
        run: ./ci/package.sh
